# Generated by Django 3.0 on 2019-12-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppStartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(default='', max_length=100)),
                ('deviceId', models.CharField(default='', max_length=100)),
                ('systemVersion', models.CharField(default='', max_length=100)),
                ('appVersionCode', models.CharField(default='', max_length=100)),
                ('memorySize', models.CharField(default='', max_length=100)),
                ('rom', models.CharField(default='', max_length=100)),
                ('supportAbi', models.CharField(default='', max_length=100)),
                ('manufacturer', models.CharField(default='', max_length=100)),
                ('isRoot', models.CharField(default='False', max_length=100)),
                ('useTime', models.CharField(default=0, max_length=50)),
                ('time', models.CharField(default=0, max_length=50)),
                ('createStartTime', models.CharField(default=0, max_length=50)),
                ('createEndTime', models.CharField(default=0, max_length=50)),
                ('fullShowCostTime', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(default='', max_length=100)),
                ('deviceId', models.CharField(default='', max_length=100)),
                ('systemVersion', models.CharField(default='', max_length=100)),
                ('appVersionCode', models.CharField(default='', max_length=100)),
                ('memorySize', models.CharField(default='', max_length=100)),
                ('rom', models.CharField(default='', max_length=100)),
                ('supportAbi', models.CharField(default='', max_length=100)),
                ('manufacturer', models.CharField(default='', max_length=100)),
                ('isRoot', models.CharField(default='False', max_length=100)),
                ('useTime', models.CharField(default=0, max_length=50)),
                ('time', models.CharField(default=0, max_length=50)),
                ('blockTime', models.CharField(default=0, max_length=50)),
                ('identifier', models.CharField(max_length=500)),
                ('pageName', models.CharField(default='', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExceptionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(default='', max_length=100)),
                ('deviceId', models.CharField(default='', max_length=100)),
                ('systemVersion', models.CharField(default='', max_length=100)),
                ('appVersionCode', models.CharField(default='', max_length=100)),
                ('memorySize', models.CharField(default='', max_length=100)),
                ('rom', models.CharField(default='', max_length=100)),
                ('supportAbi', models.CharField(default='', max_length=100)),
                ('manufacturer', models.CharField(default='', max_length=100)),
                ('isRoot', models.CharField(default='False', max_length=100)),
                ('useTime', models.CharField(default=0, max_length=50)),
                ('time', models.CharField(default=0, max_length=50)),
                ('pageName', models.CharField(default='', max_length=200)),
                ('exceptionName', models.CharField(default='', max_length=200)),
                ('thread', models.CharField(default='', max_length=100)),
                ('identifier', models.CharField(default='', max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FPSInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(default='', max_length=100)),
                ('deviceId', models.CharField(default='', max_length=100)),
                ('systemVersion', models.CharField(default='', max_length=100)),
                ('appVersionCode', models.CharField(default='', max_length=100)),
                ('memorySize', models.CharField(default='', max_length=100)),
                ('rom', models.CharField(default='', max_length=100)),
                ('supportAbi', models.CharField(default='', max_length=100)),
                ('manufacturer', models.CharField(default='', max_length=100)),
                ('isRoot', models.CharField(default='False', max_length=100)),
                ('useTime', models.CharField(default=0, max_length=50)),
                ('time', models.CharField(default=0, max_length=50)),
                ('pageName', models.CharField(default='', max_length=100)),
                ('minFps', models.IntegerField(default=0)),
                ('maxFps', models.IntegerField(default=0)),
                ('avgFps', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemoryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(default='', max_length=100)),
                ('deviceId', models.CharField(default='', max_length=100)),
                ('systemVersion', models.CharField(default='', max_length=100)),
                ('appVersionCode', models.CharField(default='', max_length=100)),
                ('memorySize', models.CharField(default='', max_length=100)),
                ('rom', models.CharField(default='', max_length=100)),
                ('supportAbi', models.CharField(default='', max_length=100)),
                ('manufacturer', models.CharField(default='', max_length=100)),
                ('isRoot', models.CharField(default='False', max_length=100)),
                ('useTime', models.CharField(default=0, max_length=50)),
                ('time', models.CharField(default=0, max_length=50)),
                ('totalSize', models.IntegerField(default=0)),
                ('vmSize', models.IntegerField(default=0)),
                ('nativeSize', models.IntegerField(default=0)),
                ('otherSize', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageSpeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(default='', max_length=100)),
                ('deviceId', models.CharField(default='', max_length=100)),
                ('systemVersion', models.CharField(default='', max_length=100)),
                ('appVersionCode', models.CharField(default='', max_length=100)),
                ('memorySize', models.CharField(default='', max_length=100)),
                ('rom', models.CharField(default='', max_length=100)),
                ('supportAbi', models.CharField(default='', max_length=100)),
                ('manufacturer', models.CharField(default='', max_length=100)),
                ('isRoot', models.CharField(default='False', max_length=100)),
                ('useTime', models.CharField(default=0, max_length=50)),
                ('time', models.CharField(default=0, max_length=50)),
                ('createStartTime', models.CharField(default=0, max_length=50)),
                ('createEndTime', models.CharField(default=0, max_length=50)),
                ('inflateFinishTime', models.CharField(default=0, max_length=50)),
                ('fullDrawFinishTime', models.CharField(default=0, max_length=50)),
                ('resumeEndTime', models.CharField(default=0, max_length=50)),
                ('pageName', models.CharField(max_length=100)),
                ('apiRequestCostStr', models.CharField(max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
