# Generated by Django 3.0 on 2019-12-12 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apmdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppPageSpeedInfo',
            new_name='PageSpeed',
        ),
    ]
