# Generated by Django 3.0 on 2019-12-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apmdb', '0002_auto_20191212_0336'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppStartInfo',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('time', models.IntegerField(default=0)),
                ('createStartTime', models.IntegerField(default=0)),
                ('createEndTime', models.IntegerField(default=0)),
                ('fullShowCostTime', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BlockInfo',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('time', models.IntegerField(default=0)),
                ('costTime', models.IntegerField(default=0)),
                ('blockIdentifier', models.CharField(max_length=200)),
                ('blockFrameStackTraceStrList', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='ExceptionInfo',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('time', models.IntegerField(default=0)),
                ('crashTraceStr', models.CharField(max_length=10000)),
                ('simpleMessage', models.CharField(max_length=1000)),
                ('threadName', models.CharField(max_length=100)),
                ('currentSystemName', models.CharField(max_length=100)),
                ('exceptionName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MemoryInfo',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('time', models.IntegerField(default=0)),
                ('totalSize', models.IntegerField(default=0)),
                ('vmSize', models.IntegerField(default=0)),
                ('nativeSize', models.IntegerField(default=0)),
                ('otherSize', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='pagespeed',
            name='apiRequestCostStr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
