# Generated by Django 3.0 on 2019-12-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apmdb', '0003_auto_20191216_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagespeed',
            name='id',
            field=models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False),
        ),
    ]
