# Generated by Django 3.0 on 2019-12-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apmdb', '0005_auto_20191216_0658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockinfo',
            old_name='costTime',
            new_name='blockTime',
        ),
        migrations.RenameField(
            model_name='blockinfo',
            old_name='blockIdentifier',
            new_name='identifier',
        ),
        migrations.RemoveField(
            model_name='blockinfo',
            name='blockFrameStackTraceStrList',
        ),
        migrations.AddField(
            model_name='blockinfo',
            name='pageName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
