# Generated by Django 3.0 on 2019-12-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apmdb', '0006_auto_20191216_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstartinfo',
            name='appVersionCode',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appstartinfo',
            name='deviceId',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appstartinfo',
            name='deviceName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appstartinfo',
            name='systemVersion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='blockinfo',
            name='appVersionCode',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='blockinfo',
            name='deviceId',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='blockinfo',
            name='deviceName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='blockinfo',
            name='systemVersion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='exceptioninfo',
            name='appVersionCode',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='exceptioninfo',
            name='deviceId',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='exceptioninfo',
            name='deviceName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='exceptioninfo',
            name='systemVersion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='memoryinfo',
            name='appVersionCode',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='memoryinfo',
            name='deviceId',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='memoryinfo',
            name='deviceName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='memoryinfo',
            name='systemVersion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pagespeed',
            name='appVersionCode',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pagespeed',
            name='deviceId',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pagespeed',
            name='deviceName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pagespeed',
            name='systemVersion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='blockinfo',
            name='identifier',
            field=models.CharField(max_length=500),
        ),
    ]
