# Generated by Django 3.0 on 2019-12-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apmdb', '0007_auto_20191216_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='FPSInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(default='', max_length=100)),
                ('deviceId', models.CharField(default='', max_length=100)),
                ('systemVersion', models.CharField(default='', max_length=100)),
                ('appVersionCode', models.CharField(default='', max_length=100)),
                ('time', models.IntegerField(default=0)),
                ('pageName', models.CharField(default='', max_length=100)),
                ('minFps', models.IntegerField(default=0)),
                ('maxFps', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
