# Generated by Django 3.0 on 2019-12-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apmdb', '0008_fpsinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstartinfo',
            name='isRoot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appstartinfo',
            name='manufacturer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appstartinfo',
            name='memorySize',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appstartinfo',
            name='rom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appstartinfo',
            name='supportAbi',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appstartinfo',
            name='useTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blockinfo',
            name='isRoot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blockinfo',
            name='manufacturer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='blockinfo',
            name='memorySize',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='blockinfo',
            name='rom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='blockinfo',
            name='supportAbi',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='blockinfo',
            name='useTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exceptioninfo',
            name='isRoot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exceptioninfo',
            name='manufacturer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='exceptioninfo',
            name='memorySize',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='exceptioninfo',
            name='rom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='exceptioninfo',
            name='supportAbi',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='exceptioninfo',
            name='useTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fpsinfo',
            name='isRoot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fpsinfo',
            name='manufacturer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fpsinfo',
            name='memorySize',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fpsinfo',
            name='rom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fpsinfo',
            name='supportAbi',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fpsinfo',
            name='useTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memoryinfo',
            name='isRoot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memoryinfo',
            name='manufacturer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='memoryinfo',
            name='memorySize',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='memoryinfo',
            name='rom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='memoryinfo',
            name='supportAbi',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='memoryinfo',
            name='useTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pagespeed',
            name='isRoot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagespeed',
            name='manufacturer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pagespeed',
            name='memorySize',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pagespeed',
            name='rom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pagespeed',
            name='supportAbi',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pagespeed',
            name='useTime',
            field=models.IntegerField(default=0),
        ),
    ]
